[package]
name = "line-chat"
version = "0.1.0"
authors = ["Javid Shamloo <javid@bellsouth.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
futures = "0.1.28"
tokio = "1.8.4"
tokio-io = "0.1.12"